-- CreateTable
CREATE TABLE "Song" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "artist" STRING,
    "key" STRING NOT NULL,
    "content" STRING,
    "dateAdded" TIMESTAMP(3),

    CONSTRAINT "Song_pkey" PRIMARY KEY ("id")
);
